language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pgehres/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pgehres/docker-react npm run test